# Generated by Django 5.2 on 2025-04-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False},
        ),
    ]
